(function(){var h=void 0,j=!0,m=null,n=!1;function u(){return function(){}}var w,x=this;function aa(a,b){var c=a.split("."),d=x;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&b!==h?d[e]=b:d=d[e]?d[e]:d[e]={}}function ba(a){a.O=function(){return a.ha?a.ha:a.ha=new a}}
function z(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ca(a){var b=z(a);return"array"==b||"object"==b&&"number"==typeof a.length}function B(a){return"string"==typeof a}function C(a){return a[da]||(a[da]=++ea)}var da="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ea=0,fa=Date.now||function(){return+new Date};function D(a,b){function c(){}c.prototype=b.prototype;a.U=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ga(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};var E,ha,ia,ja;function ka(){return x.navigator?x.navigator.userAgent:m}ja=ia=ha=E=n;var la;if(la=ka()){var ma=x.navigator;E=0==la.indexOf("Opera");ha=!E&&-1!=la.indexOf("MSIE");ia=!E&&-1!=la.indexOf("WebKit");ja=!E&&!ia&&"Gecko"==ma.product}var na=E,F=ha,G=ja,H=ia,oa=x.navigator,pa=-1!=(oa&&oa.platform||"").indexOf("Mac");function qa(){var a=x.document;return a?a.documentMode:h}var ra;
a:{var sa="",ta;if(na&&x.opera)var ua=x.opera.version,sa="function"==typeof ua?ua():ua;else if(G?ta=/rv\:([^\);]+)(\)|;)/:F?ta=/MSIE\s+([^\);]+)(\)|;)/:H&&(ta=/WebKit\/(\S+)/),ta)var va=ta.exec(ka()),sa=va?va[1]:"";if(F){var wa=qa();if(wa>parseFloat(sa)){ra=String(wa);break a}}ra=sa}var xa={};
function I(a){var b;if(!(b=xa[a])){b=0;for(var c=ga(String(ra)).split("."),d=ga(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",l=/(\d*)(\D*)/g,p=/(\d*)(\D*)/g;do{var r=l.exec(g)||["","",""],s=p.exec(k)||["","",""];if(0==r[0].length&&0==s[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==s[1].length?0:parseInt(s[1],10))?-1:(0==r[1].length?0:parseInt(r[1],10))>(0==s[1].length?0:parseInt(s[1],10))?1:0)||((0==r[2].length)<(0==s[2].length)?-1:
(0==r[2].length)>(0==s[2].length)?1:0)||(r[2]<s[2]?-1:r[2]>s[2]?1:0)}while(0==b)}b=xa[a]=0<=b}return b}var ya=x.document,za=!ya||!F?h:qa()||("CSS1Compat"==ya.compatMode?parseInt(ra,10):5);function Aa(){}var Ba=0;w=Aa.prototype;w.key=0;w.p=n;w.u=n;w.A=function(a,b,c,d,e,f){if("function"==z(a))this.ia=j;else if(a&&a.handleEvent&&"function"==z(a.handleEvent))this.ia=n;else throw Error("Invalid listener argument");this.listener=a;this.na=b;this.src=c;this.type=d;this.capture=!!e;this.R=f;this.u=n;this.key=++Ba;this.p=n};w.handleEvent=function(a){return this.ia?this.listener.call(this.R||this.src,a):this.listener.handleEvent.call(this.listener,a)};function Ca(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Da="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ea(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Da.length;f++)c=Da[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Fa=!F||F&&9<=za,Ga=F&&!I("9");!H||I("528");G&&I("1.9b")||F&&I("8")||na&&I("9.5")||H&&I("528");G&&!I("8")||F&&I("9");var J=Array.prototype,Ha=J.indexOf?function(a,b,c){return J.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(B(a))return!B(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ia=J.forEach?function(a,b,c){J.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=B(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ja=J.filter?function(a,b,c){return J.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=B(a)?
a.split(""):a,k=0;k<d;k++)if(k in g){var l=g[k];b.call(c,l,k,a)&&(e[f++]=l)}return e};var Ka=F?"focusin":"DOMFocusIn",La=F?"focusout":"DOMFocusOut";function K(){0!=Ma&&(this.Wa=Error().stack,Na[C(this)]=this)}var Ma=0,Na={};K.prototype.ba=n;K.prototype.s=function(){if(!this.ba&&(this.ba=j,this.k(),0!=Ma)){var a=C(this);delete Na[a]}};K.prototype.k=function(){this.ya&&Oa.apply(m,this.ya);if(this.la)for(;this.la.length;)this.la.shift()()};function Oa(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ca(d)?Oa.apply(m,d):d&&"function"==typeof d.s&&d.s()}};function L(a,b){this.type=a;this.currentTarget=this.target=b}w=L.prototype;w.k=u();w.s=u();w.n=n;w.defaultPrevented=n;w.F=j;w.preventDefault=function(){this.defaultPrevented=j;this.F=n};function Pa(a){Pa[" "](a);return a}Pa[" "]=u();function M(a,b){a&&this.A(a,b)}D(M,L);w=M.prototype;w.target=m;w.relatedTarget=m;w.offsetX=0;w.offsetY=0;w.clientX=0;w.clientY=0;w.screenX=0;w.screenY=0;w.button=0;w.keyCode=0;w.charCode=0;w.ctrlKey=n;w.altKey=n;w.shiftKey=n;w.metaKey=n;w.Oa=n;w.i=m;
w.A=function(a,b){var c=this.type=a.type;L.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(G){var e;a:{try{Pa(d.nodeName);e=j;break a}catch(f){}e=n}e||(d=m)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=H||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=H||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Oa=pa?a.metaKey:a.ctrlKey;this.state=a.state;this.i=a;a.defaultPrevented&&this.preventDefault();delete this.n};
w.preventDefault=function(){M.U.preventDefault.call(this);var a=this.i;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,Ga)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};w.k=u();var N={},O={},P={},Q={};
function R(a,b,c,d,e){if("array"==z(b))for(var f=0;f<b.length;f++)R(a,b[f],c,d,e);else a:{if(!b)throw Error("Invalid event type");d=!!d;var g=O;b in g||(g[b]={a:0,e:0});g=g[b];d in g||(g[d]={a:0,e:0},g.a++);var g=g[d],f=C(a),k;g.e++;if(g[f]){k=g[f];for(var l=0;l<k.length;l++)if(g=k[l],g.listener==c&&g.R==e){if(g.p)break;k[l].u=n;break a}}else k=g[f]=[],g.a++;var p=Qa,r=Fa?function(a){return p.call(r.src,r.key,a)}:function(a){a=p.call(r.src,r.key,a);if(!a)return a},l=r;l.src=a;g=new Aa;g.A(c,l,a,b,
d,e);g.u=n;c=g.key;l.key=c;k.push(g);N[c]=g;P[f]||(P[f]=[]);P[f].push(g);a.addEventListener?(a==x||!a.Z)&&a.addEventListener(b,l,d):a.attachEvent(b in Q?Q[b]:Q[b]="on"+b,l)}}function Ra(a,b,c,d,e){if("array"==z(b))for(var f=0;f<b.length;f++)Ra(a,b[f],c,d,e);else{d=!!d;a:{f=O;if(b in f&&(f=f[b],d in f&&(f=f[d],a=C(a),f[a]))){a=f[a];break a}a=m}if(a)for(f=0;f<a.length;f++)if(a[f].listener==c&&a[f].capture==d&&a[f].R==e){Sa(a[f].key);break}}}
function Sa(a){if(N[a]){var b=N[a];if(!b.p){var c=b.src,d=b.type,e=b.na,f=b.capture;c.removeEventListener?(c==x||!c.Z)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in Q?Q[d]:Q[d]="on"+d,e);c=C(c);if(P[c]){var e=P[c],g=Ha(e,b);0<=g&&J.splice.call(e,g,1);0==e.length&&delete P[c]}b.p=j;if(b=O[d][f][c])b.ka=j,Ta(d,f,c,b);delete N[a]}}}
function Ta(a,b,c,d){if(!d.B&&d.ka){for(var e=0,f=0;e<d.length;e++)d[e].p?d[e].na.src=m:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.ka=n;0==f&&(delete O[a][b][c],O[a][b].a--,0==O[a][b].a&&(delete O[a][b],O[a].a--),0==O[a].a&&delete O[a])}}function Ua(a,b,c,d,e){var f=1;b=C(b);if(a[b]){a.e--;a=a[b];a.B?a.B++:a.B=1;try{for(var g=a.length,k=0;k<g;k++){var l=a[k];l&&!l.p&&(f&=Va(l,e)!==n)}}finally{a.B--,Ta(c,d,b,a)}}return Boolean(f)}function Va(a,b){a.u&&Sa(a.key);return a.handleEvent(b)}
function Qa(a,b){if(!N[a])return j;var c=N[a],d=c.type,e=O;if(!(d in e))return j;var e=e[d],f,g;if(!Fa){var k;if(!(k=b))a:{k=["window","event"];for(var l=x;f=k.shift();)if(l[f]!=m)l=l[f];else{k=m;break a}k=l}f=k;k=j in e;l=n in e;if(k){if(0>f.keyCode||f.returnValue!=h)return j;a:{var p=n;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(r){p=j}if(p||f.returnValue==h)f.returnValue=j}}p=new M;p.A(f,this);f=j;try{if(k){for(var s=[],v=p.currentTarget;v;v=v.parentNode)s.push(v);g=e[j];g.e=g.a;for(var A=s.length-
1;!p.n&&0<=A&&g.e;A--)p.currentTarget=s[A],f&=Ua(g,s[A],d,j,p);if(l){g=e[n];g.e=g.a;for(A=0;!p.n&&A<s.length&&g.e;A++)p.currentTarget=s[A],f&=Ua(g,s[A],d,n,p)}}else f=Va(c,p)}finally{s&&(s.length=0)}return f}d=new M(b,this);return f=Va(c,d)};var Wa="StopIteration"in x?x.StopIteration:Error("StopIteration");function Xa(){}Xa.prototype.next=function(){throw Wa;};Xa.prototype.H=function(){return this};function Ya(a){if(a instanceof Xa)return a;if("function"==typeof a.H)return a.H(n);if(ca(a)){var b=0,c=new Xa;c.next=function(){for(;;){if(b>=a.length)throw Wa;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};function Za(a,b){this.j={};this.b=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof Za){c=$a(a);ab(a);for(var d=[],e=0;e<a.b.length;e++)d.push(a.j[a.b[e]])}else{var c=Ca(a),e=[],f=0;for(d in a)e[f++]=a[d];d=e}for(e=0;e<c.length;e++)this.set(c[e],d[e])}}w=Za.prototype;w.a=0;w.G=0;function $a(a){ab(a);return a.b.concat()}
w.remove=function(a){return Object.prototype.hasOwnProperty.call(this.j,a)?(delete this.j[a],this.a--,this.G++,this.b.length>2*this.a&&ab(this),j):n};function ab(a){if(a.a!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Object.prototype.hasOwnProperty.call(a.j,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.a!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Object.prototype.hasOwnProperty.call(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}}
w.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.j,a)?this.j[a]:b};w.set=function(a,b){Object.prototype.hasOwnProperty.call(this.j,a)||(this.a++,this.b.push(a),this.G++);this.j[a]=b};w.H=function(a){ab(this);var b=0,c=this.b,d=this.j,e=this.G,f=this,g=new Xa;g.next=function(){for(;;){if(e!=f.G)throw Error("The map has changed since the iterator was created");if(b>=c.length)throw Wa;var g=c[b++];return a?g:d[g]}};return g};function S(a,b){K.call(this);this.Da=b;this.M=[];if(a>this.Da)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var c=0;c<a;c++)this.M.push(this.w())}D(S,K);w=S.prototype;w.Y=m;w.aa=m;w.w=function(){return this.Y?this.Y():{}};w.$=function(a){if(this.aa)this.aa(a);else{var b=typeof a;if("object"==b&&a!=m||"function"==b)if("function"==z(a.s))a.s();else for(var c in a)delete a[c]}};w.k=function(){S.U.k.call(this);for(var a=this.M;a.length;)this.$(a.pop());delete this.M};function bb(){this.ea=[];this.ma=new Za;this.Ta=this.Ua=this.Va=this.Pa=0;this.oa=new Za;this.wa=this.Sa=0;this.Ea=1;this.Aa=new S(0,4E3);this.Aa.w=function(){return new cb};this.Qa=new S(0,50);this.Qa.w=function(){return new db};var a=this;this.fa=new S(0,2E3);this.fa.w=function(){return String(a.Ea++)};this.fa.$=u();this.Xa=3}function db(){this.ra=this.time=this.count=0}
db.prototype.toString=function(){var a=[];a.push(this.type," ",this.count," (",Math.round(10*this.time)/10," ms)");this.ra&&a.push(" [VarAlloc = ",this.ra,"]");return a.join("")};function cb(){}function eb(a,b,c,d){var e=[];-1==c?e.push("    "):e.push(fb(a.da-c));e.push(" ",gb(a.da-b));0==a.L?e.push(" Start        "):1==a.L?(e.push(" Done "),e.push(fb(a.$a-a.startTime)," ms ")):e.push(" Comment      ");e.push(d,a);0<a.Ra&&e.push("[VarAlloc ",a.Ra,"] ");return e.join("")}
cb.prototype.toString=function(){return this.type==m?this.va:"["+this.type+"] "+this.va};
bb.prototype.toString=function(){for(var a=[],b=-1,c=[],d=0;d<this.ea.length;d++){var e=this.ea[d];1==e.L&&c.pop();a.push(" ",eb(e,this.Pa,b,c.join("")));b=e.da;a.push("\n");0==e.L&&c.push("|  ")}if(0!=this.ma.a){var f=fa();a.push(" Unstopped timers:\n");d=this.ma;b=function(b){a.push("  ",b," (",f-b.startTime," ms, started at ",gb(b.startTime),")\n")};if(ca(d))try{Ia(d,b,h)}catch(g){if(g!==Wa)throw g;}else{d=Ya(d);try{for(;;)b.call(h,d.next())}catch(k){if(k!==Wa)throw k;}}}b=$a(this.oa);for(d=0;d<
b.length;d++)c=this.oa.get(b[d]),1<c.count&&a.push(" TOTAL ",c,"\n");a.push("Total tracers created ",this.Sa,"\n","Total comments created ",this.wa,"\n","Overhead start: ",this.Va," ms\n","Overhead end: ",this.Ua," ms\n","Overhead comment: ",this.Ta," ms\n");return a.join("")};function fb(a){a=Math.round(a);var b="";1E3>a&&(b=" ");100>a&&(b="  ");10>a&&(b="   ");return b+a}function gb(a){a=Math.round(a);return String(100+a/1E3%60).substring(1,3)+"."+String(1E3+a%1E3).substring(1,4)}new bb;function T(){K.call(this)}D(T,K);w=T.prototype;w.Z=j;w.T=m;w.addEventListener=function(a,b,c,d){R(this,a,b,c,d)};w.removeEventListener=function(a,b,c,d){Ra(this,a,b,c,d)};
w.dispatchEvent=function(a){var b=a.type||a,c=O;if(b in c){if(B(a))a=new L(a,this);else if(a instanceof L)a.target=a.target||this;else{var d=a;a=new L(b,this);Ea(a,d)}var d=1,e,c=c[b],b=j in c,f;if(b){e=[];for(f=this;f;f=f.T)e.push(f);f=c[j];f.e=f.a;for(var g=e.length-1;!a.n&&0<=g&&f.e;g--)a.currentTarget=e[g],d&=Ua(f,e[g],a.type,j,a)&&a.F!=n}if(n in c)if(f=c[n],f.e=f.a,b)for(g=0;!a.n&&g<e.length&&f.e;g++)a.currentTarget=e[g],d&=Ua(f,e[g],a.type,n,a)&&a.F!=n;else for(e=this;!a.n&&e&&f.e;e=e.T)a.currentTarget=
e,d&=Ua(f,e,a.type,n,a)&&a.F!=n;a=Boolean(d)}else a=j;return a};w.k=function(){T.U.k.call(this);var a,b=0,c=a==m;a=!!a;if(this==m){var d=function(d){for(var e=d.length-1;0<=e;e--){var f=d[e];if(c||a==f.capture)Sa(f.key),b++}},e;for(e in P)d.call(h,P[e])}else if(d=C(this),P[d]){d=P[d];for(e=d.length-1;0<=e;e--){var f=d[e];if(c||a==f.capture)Sa(f.key),b++}}this.T=m};var hb;function ib(){K.call(this)}D(ib,T);function jb(){K.call(this);this.d=[];this.load()}D(jb,ib);function kb(a){return a.d.filter(function(a){return"checked"==a.state}).length}jb.prototype.save=function(){try{localStorage.items=JSON.stringify(this.d)}catch(a){console.log("Err: Cannot stringify the items array",a)}};jb.prototype.load=function(){try{this.d=JSON.parse(localStorage.items)}catch(a){console.log("Err: Cannot parse the items array",a),this.d=[]}};jb.prototype.q={r:"iu"};var lb,mb=document.createElement("div");lb=function(a){mb.innerHTML=a;return mb.removeChild(mb.firstChild)};function nb(a,b){this.x=a!==h?a:0;this.y=b!==h?b:0}nb.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var ob;!G&&!F||F&&F&&9<=za||G&&I("1.9.1");F&&I("9");function pb(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function qb(a){this.ca=a||x.document||document}qb.prototype.N=function(a){return B(a)?this.ca.getElementById(a):a};qb.prototype.createElement=function(a){return this.ca.createElement(a)};qb.prototype.contains=pb;function U(a){this.f=a||document.body;R(this.f,"touchstart",this.Ma,n,this);R(this.f,"touchmove",this.La,n,this);R(this.f,"touchend",this.Ka,n,this)}ba(U);U.prototype.za=navigator.userAgent.match(/iPhone/i)&&/OS ([6-9]|\d{2})_\d/.test(navigator.userAgent);U.prototype.Ma=function(a){this.J=this.K=this.Ca=j;a=a.i;var b=a.changedTouches[0];this.touches=[a.timeStamp,b.pageX,b.pageY]};
U.prototype.La=function(a){var b=this.touches,c=a.i,d=c.changedTouches[0];if(20<Math.abs(d.pageX-b[1])||20<Math.abs(d.pageY-b[2]))this.K=n;if(this.J)if(b.push(c.timeStamp,d.pageX,d.pageY),+new Date>b[0]+100)this.J=n;else{var e=c.timeStamp,b=Ja(b,function(a,b,c){return c[b-b%3]>e-250});if(1<b.length/3){var c=new nb(b[1],b[2]),b=new nb(b[b.length-2],b[b.length-1]),d=c.x-b.x,f=c.y-b.y;60>Math.sqrt(d*d+f*f)||(c=180*Math.atan2(b.y-c.y,b.x-c.x)/Math.PI%360,b=0>360*c?c+360:c,c=rb,45<b&&135>b?c=sb:135<b&&
225>b?c=tb:225<b&&315>b&&(c=ub),b=document.createEvent("Event"),b.initEvent(c,j,j),a.target.dispatchEvent(b),this.J=n)}}};U.prototype.Ka=function(a){this.Ca=n;if(this.K){var b=this.touches,c=a.i.changedTouches[0];20<Math.abs(c.pageX-b[1])||20<Math.abs(c.pageY-b[2])?this.K=n:(b=document.createEvent("Event"),b.initEvent(vb,j,j),a=a.target,this.za&&(a=document.elementFromPoint(c.pageX-window.pageXOffset,c.pageY-window.pageYOffset)),a.dispatchEvent(b))}};function wb(a){K.call(this);R(a||document.body,["mouseover","mouseout"],this)}D(wb,T);wb.prototype.handleEvent=function(a){"mouseover"==a.type?a.relatedTarget&&!pb(a.target,a.relatedTarget)&&(a=new M(a.i),a.type=xb,this.dispatchEvent(a)):"mouseout"==a.type&&(a.relatedTarget&&!pb(a.target,a.relatedTarget))&&(a=new M(a.i),a.type=yb,this.dispatchEvent(a))};var xb="mouseenter",yb="mouseleave",vb="tap",rb="swipeRight",ub="swipeUp",tb="swipeLeft",sb="swipeDown";function V(){this.v={};this.Ya=U.O();this.Ba=new wb;R(document.body,zb,this);R(this.Ba,[xb,yb],this)}ba(V);var zb=["click","mouseover","mouseout","mousemove","mousedown","mouseup",xb,yb,vb,tb,rb,ub,sb,"scroll","keyup",Ka,La,"touchstart","touchmove","touchend"];
V.prototype.handleEvent=function(a){var b=a.target,c=b,d=[],e,f;if(f=c.getAttribute&&c.getAttribute("data-cmp"))f.split(",").forEach(function(a){a&&d.push(this.v[a])},this);else{f=[];do if(e=this.v[c.id])d.push(e),f.push(c.id);while(c=c.parentNode);b.setAttribute("data-cmp",f.join(","))}b=n;do{if(b)break;a.type==xb||a.type==yb?a.relatedTarget&&!pb(a.target,a.relatedTarget)&&(b=Ab(this,d,a)):b=Ab(this,d,a)}while(a.target=a.target.parentNode)};
function Ab(a,b,c){for(var d=n,e=0;e<b.length;e++){var f=b[e],g=f&&f.z&&f.z[c.type];if(g&&Bb(a,f,c,g,Ca(g))===n){d=j;break}}return d}function Bb(a,b,c,d,e){var f=j;Ia(e,function(a){this.matchesSelector(c.target,a)&&(f=d[a].call(b,c))},a);return f}V.prototype.matchesSelector=function(a,b){return 0<=Ha(Cb(b),a)};V.prototype.set=function(a){this.v[a.id]=a};V.prototype.remove=function(a){delete this.v[a.id]};var Db=Math.floor(2147483648*Math.random());hb=function(){return(Db++).toString(36)};var W;W=function(){return j};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var Cb;function Eb(a,b){var c=b||[];a&&c.push(a);return c}var Fb=H&&"BackCompat"==document.compatMode,Gb=document.firstChild.children?"children":"childNodes",X=n;
function Hb(a){function b(){0<=p&&(q.id=c(p,t).replace(/\\/g,""),p=-1);if(0<=r){var a=r==t?m:c(r,t);0>">~+".indexOf(a)?q.c=a:q.D=a;r=-1}0<=l&&(q.h.push(c(l+1,t).replace(/\\/g,"")),l=-1)}function c(b,c){return ga(a.slice(b,c))}a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ";for(var d=[],e=-1,f=-1,g=-1,k=-1,l=-1,p=-1,r=-1,s="",v="",A,t=0,ec=a.length,q=m,y=m;s=v,v=a.charAt(t),t<ec;t++)if("\\"!=s)if(q||(A=t,q={o:m,m:[],t:[],h:[],c:m,D:m,id:m,P:function(){return X?this.Na:this.c}},r=t),0<=e)if("]"==v){y.I?
y.S=c(g||e+1,t):y.I=c(e+1,t);if((e=y.S)&&('"'==e.charAt(0)||"'"==e.charAt(0)))y.S=e.slice(1,-1);q.t.push(y);y=m;e=g=-1}else"="==v&&(g=0<="|~^$*".indexOf(s)?s:"",y.type=g+v,y.I=c(e+1,t-g.length),g=t+1);else 0<=f?")"==v&&(0<=k&&(y.value=c(f+1,t)),k=f=-1):"#"==v?(b(),p=t+1):"."==v?(b(),l=t):":"==v?(b(),k=t):"["==v?(b(),e=t,y={}):"("==v?(0<=k&&(y={name:c(k+1,t),value:m},q.m.push(y)),f=t):" "==v&&s!=v&&(b(),0<=k&&q.m.push({name:c(k+1,t)}),q.ja=q.m.length||q.t.length||q.h.length,q.Za=q.o=c(A,t),q.Na=q.c=
q.D?m:q.c||"*",q.c&&(q.c=q.c.toUpperCase()),d.length&&d[d.length-1].D&&(q.ga=d.pop(),q.o=q.ga.o+" "+q.o),d.push(q),q=m);return d}function Y(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function Ib(a){return 1==a.nodeType}function Jb(a,b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(X?a.getAttribute(b):a.getAttribute(b,2))||""}
var Kb={"*=":function(a,b){return function(c){return 0<=Jb(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==Jb(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+Jb(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+Jb(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+Jb(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return Jb(c,a)==b}}},Lb="undefined"==
typeof document.firstChild.nextElementSibling,Mb=!Lb?"nextElementSibling":"nextSibling",Nb=!Lb?"previousElementSibling":"previousSibling",Ob=Lb?Ib:W;function Pb(a){for(;a=a[Nb];)if(Ob(a))return n;return j}function Qb(a){for(;a=a[Mb];)if(Ob(a))return n;return j}function Rb(a){var b=a.parentNode,c=0,d=b[Gb],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[Mb])Ob(b)&&(b._i=++c,a===b&&(e=c));return e}
function Sb(a){return!(Rb(a)%2)}function Tb(a){return Rb(a)%2}
var Vb={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return Pb},"last-child":function(){return Qb},"only-child":function(){return function(a){return!Pb(a)||!Qb(a)?n:j}},empty:function(){return function(a){var b=a.childNodes;for(a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return n}return j}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},
not:function(a,b){var c=Hb(b)[0],d={f:1};"*"!=c.c&&(d.c=1);c.h.length||(d.h=1);var e=Ub(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return Tb;if("even"==b)return Sb;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,g=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(g=e,e%=d));if(0<d)return function(a){a=Rb(a);return a>=f&&(0>g||a<=g)&&a%d==e};b=e}var k=parseInt(b,10);return function(a){return Rb(a)==
k}}},Wb=F?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return X?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}};
function Ub(a,b){if(!a)return W;b=b||{};var c=m;b.f||(c=Y(c,Ib));b.c||"*"!=a.c&&(c=Y(c,function(b){return b&&b.tagName==a.P()}));b.h||Ia(a.h,function(a,b){var f=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=Y(c,function(a){return f.test(a.className)});c.count=b});b.m||Ia(a.m,function(a){var b=a.name;Vb[b]&&(c=Y(c,Vb[b](b,a.value)))});b.t||Ia(a.t,function(a){var b,f=a.I;a.type&&Kb[a.type]?b=Kb[a.type](f,a.S):f.length&&(b=Wb(f));b&&(c=Y(c,b))});b.id||a.id&&(c=Y(c,function(b){return!!b&&b.id==a.id}));c||"default"in
b||(c=W);return c}var Xb={};
function Yb(a){var b=Xb[a.o];if(b)return b;var c=a.ga,c=c?c.D:"",d=Ub(a,{f:1}),e="*"==a.c,f=document.getElementsByClassName;if(c)if(f={f:1},e&&(f.c=1),d=Ub(a,f),"+"==c)var g=d,b=function(a,b,c){for(;a=a[Mb];)if(!Lb||Ib(a)){(!c||Zb(a,c))&&g(a)&&b.push(a);break}return b};else if("~"==c)var k=d,b=function(a,b,c){for(a=a[Mb];a;){if(Ob(a)){if(c&&!Zb(a,c))break;k(a)&&b.push(a)}a=a[Mb]}return b};else{if(">"==c)var l=d,l=l||W,b=function(a,b,c){for(var d=0,e=a[Gb];a=e[d++];)Ob(a)&&((!c||Zb(a,c))&&l(a,d))&&
b.push(a);return b}}else if(a.id)d=!a.ja&&e?W:Ub(a,{f:1,id:1}),b=function(b,c){var e=(b?new qb(9==b.nodeType?b:b.ownerDocument||b.document):ob||(ob=new qb)).N(a.id),f;if(f=e&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&f!=b;)f=f.parentNode;f=!!f}if(f)return Eb(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.h.length&&!Fb)var d=Ub(a,{f:1,h:1,id:1}),p=a.h.join(" "),b=function(a,b){for(var c=Eb(0,b),e,f=0,g=a.getElementsByClassName(p);e=g[f++];)d(e,a)&&c.push(e);return c};else!e&&
!a.ja?b=function(b,c){for(var d=Eb(0,c),e,f=0,g=b.getElementsByTagName(a.P());e=g[f++];)d.push(e);return d}:(d=Ub(a,{f:1,c:1,id:1}),b=function(b,c){for(var e=Eb(0,c),f,g=0,k=b.getElementsByTagName(a.P());f=k[g++];)d(f,b)&&e.push(f);return e});return Xb[a.o]=b}var $b={},ac={};
function bc(a){var b=Hb(ga(a));if(1==b.length){var c=Yb(b[0]);return function(a){if(a=c(a,[]))a.C=j;return a}}return function(a){a=Eb(a);for(var c,f,g=b.length,k,l,p=0;p<g;p++){l=[];c=b[p];f=a.length-1;0<f&&(k={},l.C=j);f=Yb(c);for(var r=0;c=a[r];r++)f(c,l,k);if(!l.length)break;a=l}return l}}var cc=!!document.querySelectorAll&&(!H||I("526"));
function dc(a,b){if(cc){var c=ac[a];if(c&&!b)return c}if(c=$b[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=j);if(cc&&!b&&-1==">~+".indexOf(c)&&(!F||-1==a.indexOf(":"))&&!(Fb&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var e=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return ac[a]=function(b){try{if(!(9==b.nodeType||d))throw"";var c=b.querySelectorAll(e);F?c.xa=j:c.C=j;return c}catch(f){return dc(a,j)(b)}}}var f=a.split(/\s*,\s*/);return $b[a]=
2>f.length?bc(a):function(a){for(var b=0,c=[],d;d=f[b++];)c=c.concat(bc(d)(a));return c}}var Z=0,fc=F?function(a){return X?a.getAttribute("_uid")||a.setAttribute("_uid",++Z)||Z:a.uniqueID}:function(a){return a._uid||(a._uid=++Z)};function Zb(a,b){if(!b)return 1;var c=fc(a);return!b[c]?b[c]=1:0}
function gc(a){if(a&&a.C)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;Z++;if(F&&X){var c=Z+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(F&&a.xa)try{for(d=1;e=a[d];d++)Ib(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=Z);for(d=1;e=a[d];d++)a[d]._zipIdx!=Z&&b.push(e),e._zipIdx=Z}return b}
function hc(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!B(a))return[a];if(B(b)&&(b=B(b)?document.getElementById(b):b,!b))return[];b=b||document;var c=b.ownerDocument||b.documentElement;X=b.contentType&&"application/xml"==b.contentType||na&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(F?c.xml:b.xmlVersion||c.xmlVersion);return(c=dc(a)(b))&&c.C?c:gc(c)}hc.m=Vb;Cb=hc;aa("goog.dom.query",Cb);aa("goog.dom.query.pseudos",Cb.m);function $(){this.id=hb();V.O().set(this);this.X()}D($,T);$.prototype.N=function(){var a=this.element;a||(a=this.element=B(this.id)?document.getElementById(this.id):this.id);return a};$.prototype.X=u();function ic(a,b){var c=m,d=a.N();d&&(c=Cb(b,d));return c}$.prototype.pa=function(){return'<div id="'+this.id+'"></div>'};$.prototype.k=function(){V.O().remove(this);this.id=this.element=m};function jc(){this.g=new jb;$.call(this)}D(jc,$);w=jc.prototype;w.X=function(){R(this.g,this.g.q.r,this.Ia,n,this)};w.Ia=function(){var a=this.g.d.map(this.qa,this).join("");ic(this,this.l.ta)[0].innerHTML=a;ic(this,this.l.V)[0].innerHTML=kc(kb(this.g))};
w.pa=function(){var a='<view id="'+this.id+'">',b;b='<h1>Today</h1><input-container><input type="text" placeholder="Type text and hit enter"></input-container><items>'+this.g.d.map(this.qa,this).join("")+"</items><footer>"+kc(kb(this.g))+"</footer>";return a+b+"</view>"};function kc(a){return!a?"":"Delete <strong>"+a+"</strong> completed tasks."}
w.qa=function(a,b){var c;c="normal"==a.state?'<i class="icon-check-false"></i>':"checked"==a.state?'<i class="icon-check-true"></i>':h;return'<item data-index="'+b+'" class="'+a.state+'"><item-delete><i class="icon-trash"></i></item-delete><item-text>'+a.text+"</item-text><item-state>"+c+"</item-state></item>"};w.Fa=function(a){var b=a.i.target;do if(a=b.getAttribute("data-index"),"ITEM"==b.tagName&&a){b=this.g;b.d.splice(a,1);b.dispatchEvent(b.q.r);b.save();break}while(b=b.parentElement)};
w.Ja=function(a){var b=a.i.target;do if(a=b.getAttribute("data-index"),"ITEM"==b.tagName&&a){b=this.g;b.d[a].state="normal"==b.d[a].state?"checked":"normal";b.dispatchEvent(b.q.r);b.save();break}while(b=b.parentElement)};w.Ga=function(){var a=this.g;a.d=a.d.filter(function(a){return"checked"!=a.state});a.dispatchEvent(a.q.r);a.save()};w.Ha=function(a){if(13==a.keyCode){a=ic(this,this.l.W)[0];var b=this.g;b.d.push({text:a.value,state:"normal"});b.dispatchEvent(b.q.r);b.save();a.value=""}};
w.l={sa:"item-delete",ua:"item-state",V:"footer",W:"input-container input",ta:"items"};(function(){this.z={};var a=this.z.keyup={},b=this.z.click={};a[this.l.W]=this.Ha;b[this.l.ua]=this.Ja;b[this.l.sa]=this.Fa;b[this.l.V]=this.Ga}).call(jc.prototype);aa("todo.Bootstrapper",function(){console.log("Bootstrapper");var a=new jc,b=document.body;b&&(a.element=lb(a.pa()),b.insertBefore(a.element,b.childNodes[h]||m))});})()
